# Generated by Django 6.0.4 on 2026-05-07 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingles',
            old_name='contenido',
            new_name='descripcion',
        ),
        migrations.RemoveField(
            model_name='ingles',
            name='tema',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='codigo',
        ),
        migrations.AlterField(
            model_name='ingles',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
