# Generated by Django 6.0.4 on 2026-05-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_contenido_ingles_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(max_length=100)),
                ('profesor', models.CharField(max_length=100)),
                ('salon', models.CharField(max_length=50)),
                ('hora', models.CharField(max_length=50)),
            ],
        ),
    ]
